### ISSUE TITLE
Filtro e ordenamento por colunas específicas na tabela de armadillhas

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/dashboard#22]

**Comment by vgeorge** [comment]
- [ ] Município*; 
- [ ] UF*; 
- [ ] Bairro*;

**Comment by miguelpeixe** [comment]
O backend permite esse request?

**Comment by vgeorge** [comment]
Sim, você pode fazer uma quero por `addressCityId` ou `addressStateId`. Por bairro não vai ser possível filtrar, pois não é um dado normalizado.

**Comment by miguelpeixe** [comment]
O filtro por cidade já é permitido na página de armadilhas e mapa. Minha dúvida é mais sobre o ordenamento.

**Comment by vgeorge** [comment]
Pois é, ordernar por id da cidade não vai adiantar muito, pois não vai estar em ordem alfabética. Vou verificar aqui https://github.com/aetrapp/aetrapp/issues/38

**Comment by vgeorge** [comment]
Implantei o ordenamento por cidade. A coluna addressCityId foi renomeada para cityId.

**Comment by miguelpeixe** [comment]
Onde está a documentação de uso? No issue do aetrapp faz referência ao readme, mas não encontrei as informações

**Comment by vgeorge** [comment]
Atualizei o readme. A chamada que ordena por uf/cidade é:

http://localhost:3030/traps?$sort[city]=1

**Comment by vgeorge** [comment]
@odascatolini Foi implantado o filtro por cidade. Não conseguimos identificar um motivo para ordenar por cidade e UF no painel, e istosobrecarregaria um pouco a interface. É possível fazer tal análise a partir do download da tabela csv das armadilhas.

**Comment by odascatolini** [comment]
@vgeorge temos que pensar esse dashboard para usuários que não tenham condições de baixar as tabelas, montar um banco de dados, montar seus próprios filtros e visualizar no QGIS. Da forma que está, um agente em nível estadual teria dificuldades para visualizar os dados de seu Estado, um agente de um bairro teria a mesma dificuldade.

Creio que seja possível permitir esse ordenamento sem sobrecarregar a interface, por exemplo:

![usabilidade-ideia-15](https://user-images.githubusercontent.com/15959483/38678309-0084b200-3e37-11e8-876c-f9fb17b1fc4a.png)

**Comment by odascatolini** [comment]
@vgeorge já foi comentado acima

**Comment by odascatolini** [comment]
Será implementado?

**Comment by vgeorge** [comment]
Aqui ainda falta resolver o ordenamento por uf/cidade

**Comment by vgeorge** [comment]
@miguelpeixe O back end agora permite o ordenamento, veja como usar aqui: https://github.com/aetrapp/api/issues/44.

**Comment by vgeorge** [comment]
Foi resolvida a questão do owner. 

Esta issue agora depende da existência do sampleCount: https://github.com/aetrapp/api/issues/48

**Comment by vgeorge** [comment]
Foi adicionado no repo master da API a propriedade sampleCount

**Comment by miguelpeixe** [comment]
Ordenação por sampleCount implementada.

**Comment by odascatolini** [comment]
@miguelpeixe 

O problema nesse ordenamento por número de ovos é que quando selecionamos decrescente aparecem primeiro as armadilhas "atrasadas" ou "aguardando amostra", sem número de ovos, então para vermos as que tem mais ovos tem que correr a paginação.

Tentei "de-selecionar" as atrasadas nos filtros, mas não é possível, pois estão implementados de forma mutualmente exclusiva, assim como estavam no mapa. Desse modo não é possível filtrar somente as armadilhas ativas de fato, excluindo as desativadas, aguardando amostra e atrasadas.

**Comment by miguelpeixe** [comment]
@odascatolini @vgeorge

Foram implementadas 2 alterações para contornar essas situações:

 - Ao selecionar um campo para ordenar a consulta é também modificada para garantir que apenas entradas com dados válidos neste campo sejam retornados, ou seja, ao ordenar as armadilhas por número de ovos, apenas armadilhas que contenham informações armazenadas são exibidas (mesmo que seja 0). Caso contrário o backend interpreta o valor `null` como maior que os valores numéricos;

 - Por conta dessa nova alteração também foi implementado um sistema que "reseta" a ordenação no 3º click, ou seja, no primeiro click é decrescente, no segundo é ascendente e o terceiro limpa a ordenação. Considerei relevante implementar esse recurso para que a ordenação seja mais fluida e siga padrões comuns e consolidados de interfaces deste tipo. Se torna especialmente relevante por conta de uma ordenação potencialmente reduzir o número de itens retornados, podendo assim intuitivamente resetar e voltar a navegação original.

Aguardando deploy para review.

**Comment by odascatolini** [comment]
ok
