### ISSUE TITLE
Download dados CSV

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/dashboard#36]
- Na tabela de armadilhas (csv) faltam os dados referentes à situação (atrasada, acima da média, etc)

- O botão "Exportar usuários" não funciona. Trocar o nome "Exportar usuários" por "Baixar usuários" para ficar como os outros

- Falta o botão "Baixar amostras" na página de amostras. Sugiro colocar o trio de botões "Baixar armadilhas", "Baixar amostras" e "Baixar usuários" nas três páginas (Armadilhas, Usuários e Amostras), como aparecem agora na página Armadilhas

- Falta aplicar os filtros no CSV que é baixado

**Comment by miguelpeixe** [comment]
cc @vgeorge sobre os dados faltantes e a possibilidade de download de CSV a partir de filtros

Os botões foram uniformizados e implementados em todas as páginas.

**Comment by vgeorge** [comment]
@miguelpeixe Implementei como um hook na rota de traps:

http://localhost:3030/traps?format=csv

Parece que o Feathers não permite setar os headers de resposta em hooks, então teria que haver um post-processamento no cliente.

**Comment by vgeorge** [comment]
Issue para acompanhar o desenvolvimento no back end: https://github.com/aetrapp/api/issues/45

**Comment by vgeorge** [comment]
@miguelpeixe As dependências de back end foram resolvidas, favor verificar.

**Comment by miguelpeixe** [comment]
Implementado download de resultados filtrados para todos os serviços (armadilhas, usuário e amostra)

**Comment by odascatolini** [comment]
Não tenho como testar porque não há dados. Aguardando cenário em João Pessoa para validar.

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

Continuamos com problemas nos status das armadilhas que impossibilitam o teste dessa funcionalidade.

**Comment by odascatolini** [comment]
@vgeorge @miguelpeixe 

- Na tabela de amostras falta uma coluna com o erro quando a amostra é inválida;
- A armadilha 7ZB76VAKD5ZHM está desativada. No entanto, ela aparece no CSV baixado após aplicação do filtro "atrasadas", com o atributo isActive=1;
- A armadilha W547GV47QJXWK foi criada em 12/05/2018, aparece no CSV das armadilhas aguardando 1a amostra. Deveria estar entre as atrasadas, mas não está;
- No CSV de usuários, falta o número de armadilhas.

**Comment by vgeorge** [comment]
Foram feitas as correções, em breve faço o deploy.

**Comment by vgeorge** [comment]
Subi à produção.

**Comment by odascatolini** [comment]
ok
