### ISSUE TITLE
Habilitar funções do usuário moderador

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/dashboard#44]
@vgeorge @miguelpeixe 

Vitor, conforme conversamos na semana passada, por uma questão de segurança é necessário um nível de acesso com poder para visualizar todos os dados de usuários de um município mas sem poder de edição. Sugiro chamar de monitor.

Quanto ao admin, falta possibilitar a edição de outros dados, como fotografia da armadilha, localização da armadilha, exclusão de amostra, etc.

**Comment by vgeorge** [comment]
@odascatolini, por favor, revise esta nova issue sobre a edição por admins #48. O único usuário com poder de edição de armadilha alheia será o admin. 

Já existe o usuário `moderador`, que é aquele que pode enviar broadcasts para as cidades, mas ele está com poder de edição no momento. Vamos restringir este poder e habilitar no front-end apenas que ele possa ver dados de contato do usuário da armadilha se ela estiver em uma cidade em que ele tem acesso.

O front-end depende da API para ser alterado. As mudanças de API necessárias estão listadas aqui: https://github.com/aetrapp/api/issues/58

**Comment by odascatolini** [comment]
@vgeorge 

A proposta aqui é:

Admin: Manter como está

Moderador: Manter como está

Regular: Manter como está

Criar novo perfil Monitor: é aquele que pode enviar broadcasts para as cidades e usuários específicos, mas sem poder de edição. Habilitar no front-end apenas que ele possa ver dados de contato do usuário da armadilha se ela estiver em uma cidade em que ele tem acesso.

**Comment by vgeorge** [comment]
@odascatolini conforme alinhamos, não será criado um novo role e o moderador terá o seu papel de editor removido. Revisando os roles, temos:

- moderador: 
  - pode enviar broadcasts diretos e para a cidade, não pode enviar broadcasts gerais; 
  - pode ver/listar usuários; 
- admin:
  - pode enviar broadcasts de qualquer tipo;
  - pode ver/listar/editar/remover usuários.

**Comment by odascatolini** [comment]
de acordo @vgeorge

**Comment by odascatolini** [comment]
Foi implementado?

**Comment by vgeorge** [comment]
Sim, faltou marcar essa.

**Comment by odascatolini** [comment]
ok
