### ISSUE TITLE
Ajuste filtros mapa

### ISSUE THREAD

**Issue by odascatolini** [aetrapp/dashboard#53]
@miguelpeixe 

Para a finalização do produto, os filtros devem ser não mutuamente exclusivos (o usuário pode selecionar mais de um ao mesmo tempo) e as armadilhas desativadas devem estar invisíveis por padrão (para visualiza-las o usuário deve ativar essa categoria nos filtros).

**Comment by miguelpeixe** [comment]
Implementado em https://github.com/aetrapp/webapp/commit/aa18ed866c761aaa530fb906b910de2dd3abcd11

![screen shot 2018-06-19 at 15 26 35](https://user-images.githubusercontent.com/820752/41616841-69629084-73d5-11e8-9117-c34211a99291.png)

**Comment by odascatolini** [comment]
Ok, @miguelpeixe ,

Mas se os filtros ativados ficam com fundo cinza, o filtro de "Desativadas" deve aparecer com fundo cinza inicialmente.

**Comment by miguelpeixe** [comment]
O fundo cinza destaca filtro **selecionado**, o branco é não selecionado.

**Comment by odascatolini** [comment]
@miguelpeixe 

Você está certo, por padrão então deveriam aparecer todas com fundo cinza, exceto as desativadas

**Comment by miguelpeixe** [comment]
Implementado, aguardando deploy para review

cc @vgeorge

**Comment by odascatolini** [comment]
ok
