### ISSUE TITLE
Renomear repositório

### ISSUE THREAD

**Issue by vgeorge** [aetrapp/dashboard#56]
Web app é um nome muito genérico para o contexto atual do projeto, sugiro a mudança para "Dashboard", que explica melhor o que este repositório contém. Aí o subtítulo ficaria "AeTrapp Dashboard" e o endereço do projeto seria: https://github.com/aetrapp/dashboard

A alteração pode ser feita aqui: https://github.com/aetrapp/webapp/settings

cc @odascatolini

**Comment by odascatolini** [comment]
@vgeorge renomeado

**Comment by vgeorge** [comment]
O nome que sugeri é `dashboard` e não `aetrapp-dashboard`.

**Comment by odascatolini** [comment]
@vgeorge desculpe, entendi errado, alterei novamente
